### ISSUE TITLE
[Teacher] Bug: Count of total student nipun is incorrect in teacher assessment history.

### ISSUE THREAD

**Issue by AakashSatpute119** [Mission-Prerna/nl-apis#204]
1.`https://api.staging.nl.samagra.io/api/school/9150202302/students/result/summary?grade=1` and 2.`https://api.staging.nl.samagra.io/api/school/9150202302/students/result/summary?grade=1,2,3`  returns successful student count diffrent.

**Comment by rohitsamagra** [comment]
- Ajay to debug

**Comment by Ajay-Maury** [comment]
The issue is coming because of the SQL query used for fetching the student's summary:- https://github.com/Mission-Prerna/nl-apis/blob/a168cfafcc03ac520662593b4fe9edee5405f868/src/school/school.service.v2.ts#L260

It fetches an assessment according to distinct student id, there can be multiple assessment records in DB for different-different subject for each students, fetching an assessment may cause the variation in It's result and nipun status.

cc:- @tushar5526

**Comment by rohitsamagra** [comment]
Aakash to schedule a call with Ajay and Rohit to discuss the logic which needs to show up

**Comment by karntrehan** [comment]
@AakashSatpute119 to test and update

**Comment by AakashSatpute119** [comment]
Tested on staging now its working as expected.

**Comment by tushar5526** [comment]
To be tested on prod.

**Comment by charanpreet-s** [comment]
@Ajay-Maury  to move this to prod
