### ISSUE TITLE
[P0] BE service alerts

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#298]
Getting multiple service alerts for BE and posthog. Need to debug the issues.

**Comment by nikhil241** [comment]
Since migrating PostHog to `nl-prod`, we’ve seen a sharp increase in requests hitting NGINX, leading to timeout issues on other services due to the high volume of open connections. To address this, we’ve applied several settings that increase NGINX’s connection handling capacity and improve PostHog’s speed and reliability.

## Enhancements Applied

### Increased File Descriptor Limits

- **`worker_rlimit_nofile 65536;`**: Raises the limit on the number of files NGINX can keep open, allowing it to handle more simultaneous connections without hitting system limits.
- **`/etc/security/limits.conf` Update**: Added the following soft and hard limits for the `www-data` user to match this higher open file limit, ensuring NGINX has adequate resources to manage increased traffic:

  ```plaintext
  www-data soft nofile 65536
  www-data hard nofile 65536

## Improved PostHog Speed and Connection Efficiency

### Keep-Alive Optimization

- **`keepalive_timeout 65;`**: Keeps connections open for 65 seconds, reducing the overhead of repeatedly establishing new connections.
- **`keepalive_requests 100;`**: Allows up to 100 requests per keep-alive connection, optimizing resource use when handling multiple requests from the same client.

### TCP Performance Settings

- **`tcp_nopush on;`**: Sends larger packets to improve network efficiency, especially helpful for loading static resources.
- **`tcp_nodelay on;`**: Sends small packets without delay, improving response times for interactive elements and API requests.

### SSL Session Optimization

- **`ssl_session_cache shared:SSL:10m;`** and **`ssl_session_timeout 1h;`**: These settings cache SSL session data, allowing faster reconnections for returning users and reducing CPU load from repeated SSL handshakes.
- **`ssl_session_tickets on;`**: Enables SSL session tickets, further optimizing the SSL handshake process for returning clients.

### Timeout Configurations for Upstream Requests

- **`proxy_connect_timeout 60s;`**, **`proxy_send_timeout 60s;`**, **`proxy_read_timeout 60s;`**: These settings provide a longer timeout window for PostHog requests to avoid premature timeouts and give the upstream server enough time to respond under heavy load.

## Outcome

With these settings, NGINX is now better equipped to handle the increased traffic and support faster, more reliable connections for PostHog, reducing the risk of timeouts and improving overall performance for end-users.

**Comment by karntrehan** [comment]
Great analysis and documentation - @nikhil241 
No alerts in the last 2 days. CPU usage stable at ~15%
Closing for now.

**Comment by karntrehan** [comment]
BE went down again between Monday and Wednesday. Posthog is down since Monday.

**Comment by karntrehan** [comment]
RCA link to be added by @dhruv-1001 and email sent. No new alerts since last week. 

Posthog events to be figured.

**Comment by dhruv-1001** [comment]
Link to [RCA](https://docs.google.com/document/d/1yEaY3rX0L8kZ9NTAj7SrCHxgBUZcU7ewMxJ0ySR_D_8/edit?tab=t.0#heading=h.df3v4ge5d6s2).

On fixing communication between docker containers.
We updated `nginx` to return 201 on any request made to `nipun.telemetry.samagra.io`, to minimise the connections made inside of the system, and so that the backend for NL can work.
Issue was that socket connection limit was reached, and the OS was not allowing nginx to make any more connections leading to failure / timeout of services, leading to health check fails, causing alerts on Discord, even through the services didn't went down.

`/etc/security/limits.conf` was updated by add
```
nginx soft nofile 65536
nginx hard nofile 65536
```
and `/etc/nginx/nginx.conf` was updated by adding
worker_rlimit_nofile 65536;

Raising the limits. No more socket limitations errors occurred.
But not the response from upstream was timing out, this was the connection from host nginx to posthog web worker.
Single instance this worker was running, leading to bottleneck. Workers were scaled up to 5 instances, and load balanced through 
host nginx.

Making these changes, have reduced load on single worked, and no more timeouts are happening now. Closing this issue.
